#!/usr/bin/env bash

EMAIL="nathan@nathan-smith.org"
PLATFORM="linux"
DOMAIN="personal"
UBUNTU=false
WSL=false

if [[ ! "${CODESPACES}" == true ]]; then
  read -n 1 -p "Installing for (1) Linux (Ubuntu), (2) Linux, (3) MacOS? " osAns;
  echo ""
  read -n 1 -p "Installing for (1) personal or (2) work? " domainAns;
  echo ""

  case $osAns in
    1)
      PLATFORM="linux"
      UBUNTU=true;;
    2)
      PLATFORM="linux";;
    3)
      PLATFORM="macos";;
    *)
      echo "Select a valid OS."
      exit 1;;
  esac

  case $domainAns in
    1)
      DOMAIN="personal";;
    2)
      DOMAIN="work";;
    *)
      echo "Select personal or work for domain"
      exit 1;;
  esac

  if [[ "${DOMAIN}" == "work" ]]; then
    read -p "What email address should be used for git? " workEmail;
    EMAIL=$workEmail
  fi

  if [[ "${PLATFORM}" == "linux" ]]; then
    read -n 1 -p "Is this a WSL linux installation? (y/N) " wslAns;
    echo ""
    case $wslAns in
      y|Y)
        WSL=true;;
    esac
  fi
fi

# Check for homebrew
if [[ "${PLATFORM}" == "macos" ]] && ! command -v brew &> /dev/null; then
  echo "install homebrew with the following /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
  exit 1
fi

# Check for zsh
if ! command -v zsh &> /dev/null; then
  echo "zsh could not be found, install it first"
  exit 1
fi

set -e

# Dotbot vars
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Clone submodules
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive

if [ -d "$ZSH" ]; then
  echo "ZSH already set; skipping Oh My Zsh install"
else
  echo "Installing Oh My Zsh:"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

echo "Installing nvm:"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash

# Remove existing zshrc if it's there
rm ~/.zshrc || true

# Setup user env
ENV_CONFIG="install.conf.yaml"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  -c "${ENV_CONFIG}" \
  "${@}"

echo "Setting git email to ${EMAIL}."
git config --global user.email "${EMAIL}"

if [[ "${PLATFORM}" == "macos" ]]; then
  echo "Recommend running the following commands:"
  echo "brew install zoxide fd fzf 1password-cli wezterm bat bat-extras less git-delta"
  echo "brew install --cask font-meslo-lg-nerd-font"
fi


if [[ ! "${PLATFORM}" == "macos" ]]; then
  echo "Recommend installing the following packages: fzf, fd, wezterm, bat, git-delta"
  echo "Recommend running the following commands:"
  echo "curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh"
fi

echo "scripts/wezterm.sh"
echo "scripts/bat-theme.sh"
echo "scripts/zsh-plugins.sh"
echo "cp loopy.zsh-theme \$ZSH_CUSTOM/themes"
echo "ln -s ${BASEDIR}/espanso \$(espanso path config)"

if [[ $UBUNTU == true ]]; then
  echo "Recommend installing nala"
fi

echo "Recommend installing the following node packages: typescript, @angular/cli, lorem-ipsum-cli, better-commits"